name: stockbot

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python main.py
